redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/jasonsmacbookpro2022/BoweryCreative/bowerycreativefrontend/dist"
publishOrigin = "config"
commandOrigin = "config"
base = "/Users/jasonsmacbookpro2022/BoweryCreative/bowerycreativefrontend"
command = "npm ci && npm run build"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]